# Generated by Django 5.0.4 on 2024-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('attendant_name', models.CharField(max_length=25)),
                ('attendant_phone', models.CharField(max_length=25)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('competencies', models.CharField(max_length=100)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('students', models.ManyToManyField(to='SMS.student')),
            ],
        ),
    ]
