# Generated by Django 5.0.4 on 2024-05-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_course_teacher_alter_teacher_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, to='SMS.teacher'),
        ),
    ]
