# Generated by Django 5.0.6 on 2024-05-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.course')),
                ('students', models.ManyToManyField(related_name='classes', to='SMS.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.teacher')),
            ],
        ),
    ]
