# Generated by Django 5.0.6 on 2024-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='SMS.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(to='SMS.student'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
